name: Publish to Docker Hub

on:
  push:
    branches:
      - main
  schedule:
   - cron: "0 0 * * *" # Runs every day at midnight to generate a new Docker image to capture upstream changes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64/v8, linux/ppc64le, linux/riscv64, linux/s390x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: dylanmtaylor/cloudflareddns-rust:latest
